apiVersion: v1
kind: Pod
metadata: 
  name: two-tier-app-pod

spec: 
  containers: 
    - name: two-tier-app-pod
      image: zunaied/flaskapp:latest
      env: 
        - name: MYSQL_HOST
          value: "myssql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_DB
          value: "mydb"
      ports: 
        - containerPort: 5000
      imagePullPolicy: Always
